### ISSUE TITLE
Change the API to use String instead of ffi::CString

### ISSUE THREAD

**Issue by kenba** [kenba/cl3#4]
It is easier for users to handle standard Rust `String`s than Rust `ffi::CString`s.  
Therefore, the API should use standard Rust `String`s or `str`s instead of `ffi::CString`s or `ffi::CStr` wherever possible.

**Comment by vmx** [comment]
In https://github.com/kenba/cl3/pull/3#pullrequestreview-617467125 I made a comment about the  [`TryFrom` trait](https://doc.rust-lang.org/std/convert/trait.TryFrom.html), here's is the explanation what I mean. `String` is a special case, so I look at the other conversions for the `InfoType` enum first.

I realized while writing this comment, that currently the conversions panic, which means that [`From`](https://doc.rust-lang.org/std/convert/trait.From.html) should be used. Hence my example is now about `From` (though it might make sense to have failable conversion, that returns a result, but that would be something for another issue).

For example the [`to_int()`](https://github.com/kenba/cl3/blob/0ca45823fddb82c0c1071202fb2ff388ab1e1d93/src/info_type.rs#L58-L63) conversation. Instead of having a method on `InfoType` it could be implemented via the `From` trait. It would look like this.

```rust
impl From<InfoType> for cl_int {
    fn from(info_type: InfoType) -> Self {
        match info_type {
            InfoType::Int(a) => a,
            _ => panic!("not a cl_int"),
        }
    }
}
```

You could then use it like this:

```rust
let value: cl_int = info_type.into();
```

I think that's more "rust-y" approach.

Why did I say `String` is a special case. You can implement `From<InfoType> for String` just the same way as for `cl_int`. Though there's another trait called [`ToString`](https://doc.rust-lang.org/std/string/trait.ToString.htm) which might make sense to implement as well (or rather `Display`, as mentioned in the docs)`.

**Comment by kenba** [comment]
Reopened to implement `From` trait etc, as described by @vmx above.

**Comment by kenba** [comment]
Changes incorporated into version 0.2.0.
