### ISSUE TITLE
Change From implementations to TryFrom

### ISSUE THREAD

**Issue by vmx** [kenba/cl3#5]
I feel a bit bad about opening this issue as I proposed implementing `From` for the `InfoType`.

Looking at the current code, I think it could be more idiomatic Rust. When I proposed implementing `From` I thought that `to_*()` methods would be removed from `InfoType` as they are redundant (I'm a fan of having only a single way of doing things). Though I can understand to keep them for backwards compatibility.

Nonetheless, if we now have both, I propose replacing the `From` implementations with `TryFrom`. This way one could decide whether one wants to panic or process the error. Let me give you a code snipped to show what I mean.

```rust
#[derive(Debug)]
pub struct InfoTypeError(String);

impl TryFrom<InfoType> for cl_int {
    type Error = InfoTypeError;

    fn try_from(info_type: InfoType) -> Result<Self, Self::Error> {
        match info_type {
            InfoType::Int(a) => Ok(a),
            _ => Err(InfoTypeError("not a cl_int".to_string())),
        }
    }
}

impl InfoType {
    pub fn to_int(self) -> cl_int {
        cl_int::try_from(self).expect("not a cl_int")
    }
}
```

Another reason to use `TryFrom` is that the [documentation for `From`](https://doc.rust-lang.org/std/convert/trait.From.html) states:

> **Note: This trait must not fail**. If the conversion can fail, use `TryFrom`.

And I'd consider a panic also as "failing" (though, I'm not sure if it matches Rusts definition)

**Comment by kenba** [comment]
> I'd consider a panic also as "failing" (though, I'm not sure if it matches Rusts definition)

The rust definition (from the Rust book) is here: [To panic! or Not to panic!](https://doc.rust-lang.org/book/ch09-03-to-panic-or-not-to-panic.html) and states "You could call panic! for any error situation". E.g. a bug in the calling program due to a programmer attempting to convert an `InfoType` into an incorrect specific type. That is *not* a "recoverable error", such as a OpenCL function returning an error code. Therefore, the conversion *cannot* fail unless the programmer writes buggy code (in which case the panic will help him/her fix their bugs), hence `From` is correct, *not* `TryFrom`.

> I thought that `to_*()` methods would be removed from `InfoType` as they are redundant

I'm fan of changes not breaking existing APIs. Volker, as you are well aware, the [opencl3](https://github.com/kenba/opencl3) is based upon this library and calls the `to_*()` methods in many places, did you expect me to rewrite them all for that change?! 

I'm also a fan of explicit code vs implicit code. The `to_*()` methods are more explicit and easier for someone to debug, if and when they call the wrong `to_*()` method on an `InfoType` than a `From`/`TryFrom` conversion would be.

> I'm a fan of having only a single way of doing things

So am I! Since the `to_*()` methods are more explicit than `From`/`TryFrom` and you can't decided between `From` and `TryFrom`, I propose deleting the `From` traits from `info_type.rs`. ;)

> I feel a bit bad about opening this issue

And so you should!

**Comment by vmx** [comment]
Thanks for the detailed reply.
